# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NWViZGY0Y2Y0NzlmM2NiMzJlNjdmODVjZTVkNzkwMmFjZTlmZWJiYWI1OTU3MTFlZjUzZmU0NzgxMGJjOGRhMTQ1ODk1YTc5ZWUxYjRkMDFkZTk2YWFkNzU2ZDYxYWRlODg2ZDliZDcyM2I2YmQ4NWIxN2JkZWU1YmIxZjA4MmM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
